name: TSMNet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=2.125=mkl
  - blas-devel=3.9.0=25_win64_mkl
  - ca-certificates=2024.8.30=h56e8100_0
  - cudatoolkit=11.1.1=hb074779_13
  - freetype=2.12.1=hdaf720e_2
  - intel-openmp=2024.2.1=h57928b3_1083
  - jpeg=8d=h8ffe710_1
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=25_win64_mkl
  - libcblas=3.9.0=25_win64_mkl
  - libdeflate=1.22=h2466b09_0
  - libgcc=14.2.0=h1383e82_1
  - libgfortran=14.2.0=h719f0c7_1
  - libgfortran5=14.2.0=hf020157_1
  - libgomp=14.2.0=h1383e82_1
  - liblapack=3.9.0=25_win64_mkl
  - liblapacke=3.9.0=25_win64_mkl
  - libpng=1.6.44=h3ca93ac_0
  - libsqlite=3.47.0=h2466b09_1
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.49.2=h2466b09_0
  - libwebp=1.4.0=h2466b09_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_8
  - libzlib=1.3.1=h2466b09_2
  - mkl=2024.2.2=h66d3029_14
  - mkl-devel=2024.2.2=h57928b3_14
  - mkl-include=2024.2.2=h66d3029_14
  - ninja=1.12.1=hc790b64_0
  - numpy=1.21.6=py37h2830a78_0
  - openssl=3.4.0=h2466b09_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.7.12=h900ac77_100_cpython
  - python_abi=3.7=4_cp37m
  - pytorch=1.9.0=py3.7_cuda11.1_cudnn8_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sqlite=3.47.0=h2466b09_1
  - tbb=2021.7.0=h91493d7_0
  - tk=8.6.13=h5226925_1
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu111
  - typing_extensions=4.7.1=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=ha32ba9b_23
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - addict==2.4.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - colorama==0.4.6
      - cycler==0.11.0
      - cython==3.0.11
      - filelock==3.12.2
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - ftfy==6.1.1
      - huggingface-hub==0.16.4
      - idna==3.10
      - importlib-metadata==6.7.0
      - kiwisolver==1.4.5
      - markdown-it-py==2.2.0
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - mmcv-full==1.3.17
      - mmdet==2.17.0
      - mmengine==0.10.5
      - mmsegmentation==0.19.0
      - opencv-python==4.10.0.84
      - packaging==24.0
      - pillow==8.2.0
      - platformdirs==4.0.0
      - prettytable==3.7.0
      - pycocotools-windows==2.0.0.2
      - pygments==2.17.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - regex==2024.4.16
      - requests==2.31.0
      - rich==13.8.1
      - safetensors==0.4.5
      - six==1.16.0
      - termcolor==2.3.0
      - terminaltables==3.1.10
      - tifffile==2021.11.2
      - timm==0.4.12
      - tomli==2.0.1
      - tqdm==4.67.0
      - urllib3==2.0.7
      - wcwidth==0.2.13
      - yapf==0.43.0
      - zipp==3.15.0
prefix: C:\Users\daijinkun\AppData\Local\anaconda3\envs\DenseCLIP_cuda111
